language: php
sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
